[package]
name = "renc-rs"
version = "0.1.0"
authors = ["Shixin Zeng <szeng@atronixengineering.com>"]
edition = "2018"

[dependencies]
failure="0.1.5"
log = "0.4.6"

[dependencies.renc-sys]
path="renc-sys"
